# Generated by Django 5.2.17 on 2026-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecolumn',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
