# Generated by Django 5.2.17 on 2026-09-14 05:09

import apps.uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.uploads.models.uploaded_document_path)),
                ('content_type', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('received', 'Received')], default='received', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
