# Generated by Django 5.2.17 on 2026-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadeddocument_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('analyzed', 'Analyzed'), ('analysis_failed', 'Analysis failed')], default='received', max_length=32),
        ),
    ]
