# Generated by Django 5.2.17 on 2026-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_uploadeddocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Extraction failed')], default='received', max_length=32),
        ),
    ]
