# Generated by Django 5.2.17 on 2026-09-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('uploads', '0003_alter_uploadeddocument_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('analyzing', 'Analyzing'), ('ready', 'Ready for column review'), ('needs_review', 'Needs review'), ('confirmed', 'Columns confirmed')], default='analyzing', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_batches', to='templates.template')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('document_type', models.CharField(default='unknown', max_length=32)),
                ('suitability', models.CharField(choices=[('suitable', 'Suitable'), ('review', 'Review recommended'), ('unsupported', 'Unsupported')], default='review', max_length=16)),
                ('page_count', models.PositiveSmallIntegerField(default=1)),
                ('is_multi_page', models.BooleanField(default=False)),
                ('has_line_items', models.BooleanField(default=False)),
                ('has_tables', models.BooleanField(default=False)),
                ('detected_summary_keys', models.JSONField(default=list)),
                ('detected_line_item_keys', models.JSONField(default=list)),
                ('custom_fields', models.JSONField(default=list)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('raw_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='processing.analysisbatch')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='uploads.uploadeddocument')),
            ],
            options={
                'ordering': ('document_id',),
            },
        ),
        migrations.CreateModel(
            name='BatchColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('summary', 'Summary'), ('line_item', 'Line items')], max_length=16)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=16)),
                ('source', models.CharField(choices=[('template', 'Template'), ('custom', 'Custom')], default='template', max_length=16)),
                ('fill_with_ai', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='processing.analysisbatch')),
                ('template_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_columns', to='templates.templatecolumn')),
            ],
            options={
                'ordering': ('dataset', 'position'),
                'constraints': [models.UniqueConstraint(fields=('batch', 'dataset', 'key'), name='unique_batch_column_key')],
            },
        ),
    ]
