# Generated by Django 5.2.17 on 2026-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcolumn',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='provider_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analysisbatch',
            name='status',
            field=models.CharField(choices=[('analyzing', 'Extracting'), ('ready', 'Ready for review'), ('needs_review', 'Needs review'), ('confirmed', 'Reviewed')], default='analyzing', max_length=24),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Extracting'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
