# Generated by Django 5.2.17 on 2026-09-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_legacy_batches_need_extraction'),
        ('templates', '0004_company_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbatch',
            name='hide_empty_columns',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysisbatch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_batches', to='templates.template'),
        ),
    ]
