# Generated by Django 5.2.17 on 2026-09-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_output_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcolumn',
            name='value_key',
            field=models.SlugField(blank=True, max_length=80),
        ),
    ]
