# Generated by Django 5.2.17 on 2026-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_analysisbatch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbatch',
            name='excel_layout',
            field=models.CharField(choices=[('invoice', 'Invoice-specific'), ('line_item', 'Line-item-specific')], default='invoice', max_length=16),
        ),
    ]
