# Generated by Django 5.2.17 on 2026-09-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_analysisbatch_excel_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisbatch',
            name='excel_layout',
        ),
    ]
